[package]
name = "os-config"
version = "0.0.1"
authors = ["Zahari Petkov <zahari@resin.io>", "Andrei Gherzan <andrei@resin.io>"]
description = "resinOS configuration tool"

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.clap]
version = "2.30"
default-features = false

[dependencies.error-chain]
version = "0.11"
default-features = false

[dev-dependencies]
assert_cli = "0.5"
pretty_env_logger = "0.2"
hyper = "0.11"
futures = "0.1"
maplit = "1.0"

[profile.release]
lto = true
