[package]
name = "os-config"
version = "0.0.1"
authors = ["Zahari Petkov <zahari@resin.io>", "Andrei Gherzan <andrei@resin.io>"]
description = "resinOS configuration tool"

[dependencies]

[dependencies.clap]
version = "2.30"
default-features = false

[dependencies.error-chain]
version = "0.11"
default-features = false
