[package]
name = "os-config"
version = "1.2.9"
authors = ["Zahari Petkov <zahari@balena.io>", "Andrei Gherzan <andrei@balena.io>"]
description = "balenaOS configuration tool"
repository = "https://github.com/balena-os/os-config"
license = "Apache-2.0"

[dependencies]
anyhow = "=1.0.2"
log = "0.4"
env_logger = "=0.6"
serde = "= 1.0.94"
serde_derive = "= 1.0.94"
serde_json = "1.0"
reqwest = "0.9"
dbus = "0.6"
hex = "0.3"
getrandom = "0.1"
base64 = "0.10"
unicode-normalization = "=0.1.9"
flate2 = "=1.0.8"
miniz_oxide_c_api = "=0.2.0"

[dependencies.clap]
version = "=2.33"
default-features = false

[dev-dependencies]
assert_cli = "0.6"
maplit = "1.0"
tempdir = "0.3"
unindent = "0.1"
actix-net = "0.2"
futures = "0.1"

[dev-dependencies.actix-web]
version = "0.7"
features = ["ssl"]

[dependencies.fatrw]
git = "https://github.com/balena-os/fatrw"
tag = "v0.1.10"

[profile.release]
opt-level = "z"
codegen-units = 1
