[package]
name = "os-config"
version = "1.2.9"
authors = ["Zahari Petkov <zahari@balena.io>", "Andrei Gherzan <andrei@balena.io>"]
description = "balenaOS configuration tool"
repository = "https://github.com/balena-os/os-config"
license = "Apache-2.0"

[dependencies]
anyhow = "=1.0.2"
log = "0.4"
env_logger = "=0.6"
serde = "= 1.0.94"
serde_derive = "= 1.0.94"
serde_json = "=1.0.44"
serde_urlencoded = "=0.5.5"
reqwest = "=0.9.24"
dbus = "0.6"
openssl = "=0.10.26"
hex = "0.3"
getrandom = "0.1"
base64 = "0.10"
unicode-normalization = "=0.1.9"
flate2 = "=1.0.8"
miniz_oxide_c_api = "=0.2.0"
indexmap = "=1.3.0"
cc = "=1.0.50"
unicode-bidi = "=0.3.4"
cookie_store = "=0.7.0"
failure = "=0.1.6"
rustc-demangle = "=0.1.16"
backtrace = "=0.3.41"
ryu = "=1.0.2"
regex-syntax = "=0.6.13"
regex = "=1.3.3"
thread_local = "=1.0.1"
httparse = "=1.3.4"
encoding_rs = "=0.8.22"
openssl-sys = "=0.9.53"
idna = "=0.2.0"
url = "=2.1.1"

[dependencies.clap]
version = "=2.33"
default-features = false

[dev-dependencies]
assert_cli = "0.6"
maplit = "1.0"
tempdir = "0.3"
unindent = "0.1"
actix-net = "0.2"
futures = "0.1"

[dev-dependencies.actix-web]
version = "0.7"
features = ["ssl"]

[dependencies.fatrw]
git = "https://github.com/balena-os/fatrw"
tag = "v0.1.10"

[profile.release]
opt-level = "z"
codegen-units = 1
