[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = {version = "4.1", default-features = false, features = ["rustls"]}
base64 = "0.21"
serde_json = "1"
tempfile = "3"
unindent = "0.1"
pem = "0.8"
rustls = "0.20"
rcgen = "0.9"
