version: 2

jobs:
  test:
    docker:
      - image: majorz/rust-test-deploy:rust-nightly-2018-02-19
    steps:
      - checkout

      - run: cargo fmt -- --write-mode=diff
      - run: cargo clippy -- -D warnings
      - run: cargo test

workflows:
  version: 2
  test:
    jobs:
      - test
